apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/demo-app-deployment.git
  username: root
  password: cgXdWrL60g3A7EZP3a7FvStK4ZZOADHgg5I8ydI8wwUTuxuUAdYMFqJVezbYfffx