MASTER_IP = "192.168.56.110"

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.provider "libvirt" do |v|
        v.memory = 2048
        v.cpus = 2
        v.driver = "kvm"
    end

    config.vm.define "arbutnarS" do |control|
        control.vm.hostname = "arbutnarS"
        control.vm.network "private_network", ip: MASTER_IP
        control.vm.provision "shell", inline: <<-SHELL
            apt-get update && apt-get install -y curl

            curl -sSLf https://get.k3s.io  > /tmp/k3s-install.sh
            sh /tmp/k3s-install.sh --write-kubeconfig-mode 644 --node-ip=#{MASTER_IP} --advertise-address=#{MASTER_IP} --flannel-iface="eth1"

            kubectl apply -f /vagrant
        SHELL
    end

end
