MASTER_IP = "192.168.56.110"

Vagrant.configure(2) do |config|
    config.vm.box = "generic/debian12"

    config.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
        v.driver = "kvm"
    end

    config.vm.define "arbutnarS", primary: true do |control|
        control.vm.hostname = "arbutnarS"
        control.vm.network "private_network", ip: MASTER_IP
        control.vm.provision "shell", inline: <<-SHELL
            curl -sfL https://get.k3s.io  > /tmp/k3s-install.sh
            sh /tmp/k3s-install.sh --write-kubeconfig-mode 644 --node-ip=#{MASTER_IP} --advertise-address=#{MASTER_IP} --flannel-iface="eth1"
        SHELL
    end

    config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
end

# paulbouwer/hello-kubernetes