K3S_TOKEN = "mysecrettoken123"
MASTER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true

    config.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
        v.driver = "kvm"
    end

    config.vm.define "arbutnarS", primary: true do |control|
        control.vm.hostname = "arbutnarS"
        control.vm.network "private_network",
            ip: MASTER_IP,
            libvirt__network_name: "iot",
            libvirt__dhcp_enabled: false,
            libvirt__forward_mode: "nat"

        control.vm.provision "shell", inline: <<-SHELL
            apt-get update -y && apt-get install -y curl
            curl -sSfL https://get.k3s.io  > /tmp/k3s-install.sh
            
            K3S_TOKEN=#{K3S_TOKEN} \
            sh /tmp/k3s-install.sh --write-kubeconfig-mode 644 --node-ip=#{MASTER_IP} --advertise-address=#{MASTER_IP} --flannel-iface="eth1"
        SHELL
    end

    config.vm.define "arbutnarSW" do |control|
        control.vm.hostname = "arbutnarSW"
        control.vm.network "private_network",
            ip: WORKER_IP,
            libvirt__network_name: "iot",
            libvirt__dhcp_enabled: false,
            libvirt__forward_mode: "nat"

        control.vm.provision "shell", inline: <<-SHELL
            apt-get update && apt-get install -y curl
            curl -sSfL https://get.k3s.io > /tmp/k3s-install.sh

            K3S_URL=https://#{MASTER_IP}:6443 \
            K3S_TOKEN=#{K3S_TOKEN} \
            sh /tmp/k3s-install.sh --node-ip=#{WORKER_IP}
        SHELL
    end
end