MASTER_IP = "192.168.56.113"

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true

    config.vm.provider "libvirt" do |v|
        v.memory = 6144
        v.cpus = 4
        v.driver = "kvm"
    end

    config.vm.define "arbutnarS" do |control|
        control.vm.hostname = "arbutnarS"
        control.vm.network "private_network", ip: MASTER_IP
        control.vm.provision "shell", path: "../p3/scripts/init.sh"
        control.vm.provision "shell", inline: <<-SHELL

            # Install Helm
            curl -fsSL -o /tmp/helm.tar.gz "https://get.helm.sh/helm-v4.0.0-linux-amd64.tar.gz"
            tar -xzf /tmp/helm.tar.gz -C /tmp
            install -o root -g root -m 0755 /tmp/linux-amd64/helm /usr/local/bin/helm
            rm -rf /tmp/helm.tar.gz /tmp/linux-amd64

            # Deploy GitLab via Helm
            kubectl create namespace gitlab
            helm repo add gitlab http://charts.gitlab.io/
            helm repo update
            helm upgrade --install gitlab gitlab/gitlab -n gitlab \
                --version 9.6.1 \
                --set installCertmanager=false \
                --set global.ingress.configureCertmanager=false \
                --set gitlab-runner.install=false \
                --set global.kas.enabled=false \
                --set prometheus.install=false \
                --set postgresql.metrics.enabled=false \
                --set redis.metrics.enabled=false \
                --set gitlab.gitlab-exporter.enabled=false \
                --set global.grafana.enabled=false \
                --set gitlab.gitlab-pages.enabled=false \
                --set registry.enabled=false \
                --set gitlab.webservice.minReplicas=1 \
                --set gitlab.webservice.maxReplicas=1 \
                --set gitlab.sidekiq.minReplicas=1 \
                --set gitlab.sidekiq.maxReplicas=1 \
                --set gitlab.gitlab-shell.minReplicas=1 \
                --set gitlab.gitlab-shell.maxReplicas=1 \
                --set nginx-ingress.controller.replicaCount=1 \
                --set nginx-ingress.controller.service.type=NodePort \
                --wait --timeout 900s

            # Display initial GitLab root password
            RESET='\e[0m'
            CYAN='\e[1;36m'
            echo -e "$CYAN$(kubectl get secret -n gitlab gitlab-gitlab-initial-root-password -ojsonpath='{.data.password}' 2>/dev/null | base64 --decode)$RESET"

            # kubectl port-forward -n argocd svc/argocd-server 443:443 --address 0.0.0.0
        SHELL
        control.vm.provision "shell", path: "../p3/scripts/deploy_argocd.sh", args: ["#{MASTER_IP}", "443"]
    end

end
