MASTER_IP = "192.168.56.112"

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.provider "libvirt" do |v|
        v.memory = 4056
        v.cpus = 2
        v.driver = "kvm"
    end

    config.vm.define "arbutnarS" do |control|
        control.vm.hostname = "arbutnarS"
        control.vm.network "private_network", ip: MASTER_IP

        control.vm.provision "shell", path: "scripts/init.sh"
        control.vm.provision "shell", path: "scripts/create_cluster.sh"
        control.vm.provision "shell", path: "scripts/setup_kubeconfig.sh"
        control.vm.provision "shell", path: "scripts/deploy_argocd.sh"
        control.vm.provision "shell", inline: <<-SHELL
            kubectl apply -f /vagrant/confs/application.yaml
        SHELL
        control.vm.provision "shell", run: "always", path: "scripts/get_argocd_info.sh"
    end

end
