MASTER_IP = "192.168.56.112"

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true

    config.vm.provider "libvirt" do |v|
        v.memory = 4056
        v.cpus = 2
        v.driver = "kvm"
    end

    config.vm.define "arbutnarS" do |control|
        control.vm.hostname = "arbutnarS"
        control.vm.network "private_network", ip: MASTER_IP

        control.vm.provision "shell", path: "scripts/provision.sh"
        control.vm.provision "shell", inline: <<-SHELL
            # Create argocd application
            kubectl apply -n argocd -f https://raw.githubusercontent.com/arbutnar/Inception-of-Things_p3/refs/heads/main/application.yaml
            # Port-forward argocd server 
            kubectl port-forward -n argocd svc/argocd-server 443:443 --address 0.0.0.0
        SHELL
    end

end
